language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install -r requirements.txt
script: make test

# HACK needed for bad Boto config on TravisCI https://github.com/travis-ci/travis-ci/issues/7940
sudo: false
